{
    trafficRegistrationPoints {
        id
        name
        latestData {
            volumeByHour
        }
        location {
            coordinates {
                latLon {
                    lat
                    lon
                }
            }
        }
    }
}
